/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue.ajout;

import be.isfce.tfe.db.MrutilisationDBHelper;
import be.isfce.tfe.metier.MrUtilisation;

/**
 *
 * @author yema
 */
public class MrutilisationJPanell extends javax.swing.JPanel {

    /**
     * Creates new form MrutilisationJPanell
     */
    public MrutilisationJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idvehiculeTextField = new javax.swing.JTextField();
        idutilisationTextField = new javax.swing.JTextField();
        validerjButton = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();

        jLabel1.setText("Identifiant vehicule:");

        jLabel2.setText("Identifiant utilisation:");

        validerjButton.setText("Valider");
        validerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerjButtonActionPerformed(evt);
            }
        });

        Annuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Annuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(validerjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idvehiculeTextField)
                            .addComponent(idutilisationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idvehiculeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(idutilisationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validerjButton)
                    .addComponent(Annuler))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerjButtonActionPerformed
        // TODO add your handling code here:
         MrUtilisation mrutilisation = new MrUtilisation();
         String idvehicule = idvehiculeTextField.getText();
         mrutilisation.setId(String.valueOf(idvehicule));
         System.out.println(idvehicule);
         
         String idutilisation = idutilisationTextField.getText();
         mrutilisation.setIdutilisation(Integer.valueOf(idutilisation));
         System.out.println(idvehicule);
        
        
        MrutilisationDBHelper.addMrUtilisation(mrutilisation);
        MrutilisationDBHelper.selectMrUtilisation(mrutilisation);
    }//GEN-LAST:event_validerjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField idutilisationTextField;
    private javax.swing.JTextField idvehiculeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton validerjButton;
    // End of variables declaration//GEN-END:variables
}
