/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;

import be.isfce.tfe.metier.Chauffeur;
import java.util.Date;

/**
 *
 * @author yema
 */
public class AjoutChauffeurJPanell extends javax.swing.JPanel {

    /**
     * Creates new form AjoutChauffeurJPanell
     */
    public AjoutChauffeurJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idChauffeur = new javax.swing.JLabel();
        nomChauffeur = new javax.swing.JLabel();
        prenomChauffeur = new javax.swing.JLabel();
        AdresseChauffeur = new javax.swing.JLabel();
        dateChauffeur = new javax.swing.JLabel();
        numChauffeur = new javax.swing.JLabel();
        emailChauffeur = new javax.swing.JLabel();
        smChauffeur = new javax.swing.JLabel();
        registreNationalTextField = new javax.swing.JTextField();
        nomchauffeurTextField = new javax.swing.JTextField();
        prenomTextField = new javax.swing.JTextField();
        adresseTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        numTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        smTextField = new javax.swing.JTextField();
        modification = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        enregistrerChauffeur = new javax.swing.JButton();
        codepostale = new javax.swing.JLabel();
        codepostaleTextField = new javax.swing.JTextField();
        ville = new javax.swing.JLabel();
        villeTextField = new javax.swing.JTextField();
        validitercap = new javax.swing.JLabel();
        validitercapTextField = new javax.swing.JTextField();
        cartechauffeurLabel = new javax.swing.JLabel();
        validitercartechauffeurTextField1 = new javax.swing.JTextField();

        idChauffeur.setText("registre national:");

        nomChauffeur.setText("Nom :");

        prenomChauffeur.setText("Prenom :");

        AdresseChauffeur.setText("Adresse:");

        dateChauffeur.setText("Date de naissance:");

        numChauffeur.setText("Numero de telephone:");

        emailChauffeur.setText("Email:");

        smChauffeur.setText("Validiter selection medicale:");

        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        modification.setText("Reset");
        modification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationActionPerformed(evt);
            }
        });

        retour.setText("Annuler");

        enregistrerChauffeur.setText("Enregistrer");
        enregistrerChauffeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerChauffeurActionPerformed(evt);
            }
        });

        codepostale.setText("Code postale:");

        ville.setText("Ville:");

        validitercap.setText("Validiter CAP:");

        cartechauffeurLabel.setText("Validiter carte chauffeur:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(validitercap)
                            .addComponent(modification))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enregistrerChauffeur)
                                    .addComponent(retour))
                                .addGap(254, 254, 254))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(validitercapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idChauffeur)
                            .addComponent(nomChauffeur)
                            .addComponent(prenomChauffeur)
                            .addComponent(dateChauffeur)
                            .addComponent(AdresseChauffeur)
                            .addComponent(ville)
                            .addComponent(smChauffeur)
                            .addComponent(emailChauffeur, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartechauffeurLabel)
                            .addComponent(numChauffeur))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomchauffeurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(villeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                .addComponent(smTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(registreNationalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codepostale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codepostaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(validitercartechauffeurTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(206, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idChauffeur)
                            .addComponent(registreNationalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomChauffeur)
                            .addComponent(nomchauffeurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prenomChauffeur)
                            .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChauffeur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdresseChauffeur)
                            .addComponent(adresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codepostale)
                            .addComponent(codepostaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ville)
                            .addComponent(villeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numChauffeur)
                            .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailChauffeur))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smChauffeur)
                            .addComponent(smTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartechauffeurLabel)
                            .addComponent(validitercartechauffeurTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(validitercap))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(validitercapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(retour)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enregistrerChauffeur)
                    .addComponent(modification))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificationActionPerformed

    private void enregistrerChauffeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerChauffeurActionPerformed
        // TODO add your handling code here:
        Chauffeur chauffeur = new Chauffeur();
        String registreNational = registreNationalTextField.getText();
        registreNational = registreNational.replace("-", "");
        registreNational = registreNational.replace(".", "");
        if (!checkRegistreNational(registreNational)) {
            //TODO Afficher dialog d'erreur
            //Check a retourné false : Le chauffeur ne peut être créé.
            System.out.println("REGISTRE NATIONAL INCORRECT");
        } else {
            chauffeur.setId(Long.valueOf(registreNational));
            //Sinon je peux setté son attribut avec la valeur récupérée.
            System.out.println("REGISTRE NATIONAL CORRECT");
        }

        String nomChauffeur = nomchauffeurTextField.getText();
        if(!VerifString(nomChauffeur)){
             System.out.println(" NOM INCORRECT");}
        else{
            
            chauffeur.setNomChauffeur(String.valueOf(nomChauffeur));
            System.out.println("NOM CORRECT");
        }

        String prenom = prenomTextField.getText();
        if(!VerifString(prenom)){
             System.out.println(" PRENOM INCORRECT");}
        else{
            
            chauffeur.setPrenomChauffeur(String.valueOf(prenomChauffeur));
            System.out.println("PRENOM CORRECT");
        }
        

        String adresse = adresseTextField.getText();
        chauffeur.setAdresse(adresse);
        
        String codepostale = codepostaleTextField.getText();
        if (!checkCodePostale(codepostale)) {
            
            System.out.println("CODE POSTALE INCORRECT");
        } else {
            chauffeur.setCodepostale(Long.valueOf(codepostale));
            
            System.out.println("CODE POSTALE CORRECT");
        }
        
         String ville = villeTextField.getText();
         VerifString(ville);
         chauffeur.setVille(ville);
         
          String numtel = numTextField.getText();
          checkNumTel(numtel);
          numtel = numtel.replace("-", "");
          numtel = numtel.replace(".", "");
          numtel = numtel.replace("/", "");
          chauffeur.setNumTelephone(Long.valueOf(numtel));
          
          String email = emailTextField.getText();
          chauffeur.setEmail(email);
          
          
          
          
      
         
        

        
        
        


        //TODO A faire avec tous les attributs.


        //TODO Ajouter le chauffeur à la base de données.
    }

    private boolean checkRegistreNational(String registreNational) {

        if (registreNational == null || registreNational.isEmpty()) {
            System.out.println("veuillez inserer une donnée svp");
            return false;
        }
        if (registreNational.length() != 11) {
            System.out.println("veuillez introduire le bon format");
            return false;
        }
        try {
            Long.valueOf(registreNational);
        } catch (NumberFormatException e) {
            System.out.println("Error");
            e.printStackTrace();
            return false;
        }
        return true;



    }//GEN-LAST:event_enregistrerChauffeurActionPerformed
     private boolean checkCodePostale(String codepostale) {

        if (codepostale == null || codepostale.isEmpty()) {
            System.out.println("veuillez inserer une donnée svp");
            return false;
        }
        if (codepostale.length()<= '4'&& codepostale.length()<'6') {
            System.out.println("veuillez introduire le bon format");
            return false;
        }
        try {
            Long.valueOf(codepostale);
        } catch (NumberFormatException e) {
            System.out.println("Error");
            e.printStackTrace();
            return false;
        }
        return true;



    } 
      private boolean checkNumTel(String numtel) {

        if (numtel == null || numtel.isEmpty()) {
            System.out.println("veuillez inserer une donnée svp");
            return false;
        }
        if (numtel.length() != 9 || numtel.length()!= 10 ) {
            System.out.println("veuillez introduire le bon format");
            return false;
        }
        try {
            Long.valueOf(numtel);
        } catch (NumberFormatException e) {
            System.out.println("Error");
            e.printStackTrace();
            return false;
        }
        return true;



    }                                                    

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private boolean VerifString(String caractere) {
        if (caractere == null || caractere.isEmpty()) {
            System.out.println("veuillez inserer une donnée svp");
            return false;
        }
        for (int i = 0; i < caractere.length(); i++) {
            if (caractere.charAt(i) == '1' || caractere.charAt(i) == '2' || caractere.charAt(i) == '3' || caractere.charAt(i) == '4'
                    || caractere.charAt(i) == '5' || caractere.charAt(i) == '6' || caractere.charAt(i) == '7' || caractere.charAt(i) == '8'
                    || caractere.charAt(i) == '9' || caractere.charAt(i) == '0') {
                System.out.println("veuillez rentrer une donnée correcte");

                return false;
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdresseChauffeur;
    private javax.swing.JTextField adresseTextField;
    private javax.swing.JLabel cartechauffeurLabel;
    private javax.swing.JLabel codepostale;
    private javax.swing.JTextField codepostaleTextField;
    private javax.swing.JLabel dateChauffeur;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel emailChauffeur;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton enregistrerChauffeur;
    private javax.swing.JLabel idChauffeur;
    private javax.swing.JButton modification;
    private javax.swing.JLabel nomChauffeur;
    private javax.swing.JTextField nomchauffeurTextField;
    private javax.swing.JLabel numChauffeur;
    private javax.swing.JTextField numTextField;
    private javax.swing.JLabel prenomChauffeur;
    private javax.swing.JTextField prenomTextField;
    private javax.swing.JTextField registreNationalTextField;
    private javax.swing.JButton retour;
    private javax.swing.JLabel smChauffeur;
    private javax.swing.JTextField smTextField;
    private javax.swing.JLabel validitercap;
    private javax.swing.JTextField validitercapTextField;
    private javax.swing.JTextField validitercartechauffeurTextField1;
    private javax.swing.JLabel ville;
    private javax.swing.JTextField villeTextField;
    // End of variables declaration//GEN-END:variables
}
