/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;

import be.isfce.tfe.metier.MaterielRoulant;



/**
 *
 * @author yema
 */
public class AjoutMateielRoulantJPanell extends javax.swing.JPanel {

    /**
     * Creates new form AjoutMateielRoulantJPanell
     */
    public AjoutMateielRoulantJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idvehicule = new javax.swing.JLabel();
        marquevehicule = new javax.swing.JLabel();
        typevehicule = new javax.swing.JLabel();
        numimmatr = new javax.swing.JLabel();
        carburant = new javax.swing.JLabel();
        nbplaces = new javax.swing.JLabel();
        identifiantTextField = new javax.swing.JTextField();
        marqueTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        plaqueTextField = new javax.swing.JTextField();
        carburantTextField = new javax.swing.JTextField();
        nbdeplaceTextField = new javax.swing.JTextField();
        ajoutervehicule = new javax.swing.JToggleButton();
        modifiervehicule = new javax.swing.JToggleButton();
        supprimervehicule = new javax.swing.JToggleButton();
        kilometrage = new javax.swing.JLabel();
        kilometrageTextField = new javax.swing.JTextField();

        idvehicule.setText("Identifiant:");

        marquevehicule.setText("Marque:");

        typevehicule.setText("Type:");

        numimmatr.setText("Plaque immatriculation:");

        carburant.setText("Carburant:");

        nbplaces.setText("Nombres de Places:");

        marqueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marqueTextFieldActionPerformed(evt);
            }
        });

        plaqueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaqueTextFieldActionPerformed(evt);
            }
        });

        ajoutervehicule.setText("Enregistrer");
        ajoutervehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutervehiculeActionPerformed(evt);
            }
        });

        modifiervehicule.setText("Reset");
        modifiervehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifiervehiculeActionPerformed(evt);
            }
        });

        supprimervehicule.setText("Annuler");

        kilometrage.setText("Kilometrage:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marquevehicule)
                            .addComponent(idvehicule))
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(identifiantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(marqueTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addComponent(ajoutervehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(modifiervehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(supprimervehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numimmatr)
                            .addComponent(typevehicule)
                            .addComponent(carburant)
                            .addComponent(nbplaces)
                            .addComponent(kilometrage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nbdeplaceTextField)
                            .addComponent(carburantTextField)
                            .addComponent(typeTextField)
                            .addComponent(plaqueTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kilometrageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idvehicule)
                    .addComponent(identifiantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marquevehicule)
                    .addComponent(marqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typevehicule)
                    .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numimmatr)
                    .addComponent(plaqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carburant)
                    .addComponent(carburantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbplaces)
                    .addComponent(nbdeplaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kilometrage)
                    .addComponent(kilometrageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutervehicule)
                    .addComponent(modifiervehicule)
                    .addComponent(supprimervehicule))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifiervehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifiervehiculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifiervehiculeActionPerformed

    private void marqueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marqueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marqueTextFieldActionPerformed

    private void plaqueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaqueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plaqueTextFieldActionPerformed

    private void ajoutervehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutervehiculeActionPerformed
        // TODO add your handling code here:
        MaterielRoulant materielroulant = new MaterielRoulant();
        
         String id = identifiantTextField.getText();
        materielroulant.setId(Integer.valueOf(id));
        System.out.println(id);
        
        

        String marque = marqueTextField.getText();
        if(!VerifString(marque)){
             System.out.println(" MARQUE INCORRECT");}
        else{
            
            materielroulant.setMarque(String.valueOf(marque));
            System.out.println(marque);
        }

        String type = typeTextField.getText();
        if(!VerifString(type)){
             System.out.println("  TYPE INCORRECT");}
        else{
            
            materielroulant.setType(String.valueOf(type));
            System.out.println(type);
        }
        
        String plaque = plaqueTextField.getText();
        plaque = plaque.replace(".", "");
        plaque = plaque.replace("-", "");
        materielroulant.setNumImmatr(plaque);
        System.out.println(plaque);
        
        
          String carburant = carburantTextField.getText();
        if(!VerifString(type)){
             System.out.println("  Carburant INCORRECT");}
        else{
            
            materielroulant.setType(String.valueOf(carburant));
            System.out.println(carburant);
        }
        
          String nbdeplace = nbdeplaceTextField.getText();
        materielroulant.setNbDePlaces(Integer.valueOf(nbdeplace));
        System.out.println(nbdeplace);
        
         String kilometrage = kilometrageTextField.getText();
        materielroulant.setKmactuel(Integer.valueOf(nbdeplace));
        System.out.println(kilometrage);
        
        
        
        

    }//GEN-LAST:event_ajoutervehiculeActionPerformed
  
                
      private boolean VerifString(String caractere) {
        if (caractere == null || caractere.isEmpty()) {
            System.out.println("veuillez inserer une donnée svp");
            return false;
        }
        for (int i = 0; i < caractere.length(); i++) {
            if (caractere.charAt(i) == '1' || caractere.charAt(i) == '2' || caractere.charAt(i) == '3' || caractere.charAt(i) == '4'
                    || caractere.charAt(i) == '5' || caractere.charAt(i) == '6' || caractere.charAt(i) == '7' || caractere.charAt(i) == '8'
                    || caractere.charAt(i) == '9' || caractere.charAt(i) == '0') {
                System.out.println("veuillez rentrer une donnée correcte");

                return false;
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ajoutervehicule;
    private javax.swing.JLabel carburant;
    private javax.swing.JTextField carburantTextField;
    private javax.swing.JTextField identifiantTextField;
    private javax.swing.JLabel idvehicule;
    private javax.swing.JLabel kilometrage;
    private javax.swing.JTextField kilometrageTextField;
    private javax.swing.JTextField marqueTextField;
    private javax.swing.JLabel marquevehicule;
    private javax.swing.JToggleButton modifiervehicule;
    private javax.swing.JTextField nbdeplaceTextField;
    private javax.swing.JLabel nbplaces;
    private javax.swing.JLabel numimmatr;
    private javax.swing.JTextField plaqueTextField;
    private javax.swing.JToggleButton supprimervehicule;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JLabel typevehicule;
    // End of variables declaration//GEN-END:variables
}
