/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;

import be.isfce.tfe.db.EntretienDBHelper;
import be.isfce.tfe.metier.Entretien;
import be.isfce.tfe.validation.StringValidation;
import java.util.Date;

/**
 *
 * @author yema
 */
public class AjoutEntretienJPanell extends javax.swing.JPanel {

    /**
     * Creates new form AjoutEntretienJPanell
     */
    public AjoutEntretienJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identretien = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        kmactuel = new javax.swing.JLabel();
        dateentretien = new javax.swing.JLabel();
        identretienTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        kmactuelTextField = new javax.swing.JTextField();
        ajouter = new javax.swing.JToggleButton();
        modifier = new javax.swing.JToggleButton();
        supprimer = new javax.swing.JToggleButton();
        dateentretienfait = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        idvehiculeTextField = new javax.swing.JTextField();

        identretien.setText("Identifiant Entretien:");

        description.setText("Description:");

        kmactuel.setText("Kilométrage actuel:");

        dateentretien.setText("Date entretien:");

        ajouter.setText("Enregistrer");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setText("Reset");

        supprimer.setText("Annuler");

        jLabel1.setText("Identifiant vehicule:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(identretien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kmactuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateentretien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(identretienTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addComponent(descriptionTextField)
                                .addComponent(kmactuelTextField))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idvehiculeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateentretienfait, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identretien)
                    .addComponent(identretienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kmactuel)
                    .addComponent(kmactuelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateentretien)
                    .addComponent(dateentretienfait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idvehiculeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(modifier)
                    .addComponent(supprimer))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        Entretien entretien = new Entretien();
        String identretien = identretienTextField.getText();
        entretien.setId(0);
        System.out.println(identretien);
        
          String description = descriptionTextField.getText();
        if(!StringValidation.VerifString(description)){
             System.out.println(" NOM INCORRECT");}
        else{
            
            entretien.setDescription(String.valueOf(description));
            System.out.println(description);
        }
        
        String kmactuel = kmactuelTextField.getText();
        entretien.setKmEntretienFait(Integer.valueOf(kmactuel));
        System.out.println(kmactuel);
        
         Date dateEntretien = dateentretienfait.getDate();
        if(dateEntretien!= null){
            entretien.setDateEntretien(dateEntretien );
            System.out.println(dateEntretien);
        }else{
            System.out.println("DATE ENTRETIEN INCORRECTE");
        } 
        
         String idvehicule = idvehiculeTextField.getText();
         entretien.setIdmaterielroulant(String.valueOf(idvehicule));
         System.out.println(idvehicule);
        
        EntretienDBHelper.addEntretien(entretien);
        EntretienDBHelper.selectEntretien(entretien);     
    }//GEN-LAST:event_ajouterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ajouter;
    private javax.swing.JLabel dateentretien;
    private com.toedter.calendar.JDateChooser dateentretienfait;
    private javax.swing.JLabel description;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel identretien;
    private javax.swing.JTextField identretienTextField;
    private javax.swing.JTextField idvehiculeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kmactuel;
    private javax.swing.JTextField kmactuelTextField;
    private javax.swing.JToggleButton modifier;
    private javax.swing.JToggleButton supprimer;
    // End of variables declaration//GEN-END:variables
}
