/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;

import be.isfce.tfe.db.EcoleDBHelper;
import be.isfce.tfe.metier.Ecole;
import be.isfce.tfe.validation.CodePosalValidation;
import be.isfce.tfe.validation.EmailValidation;
import be.isfce.tfe.validation.NumTelValidation;
import be.isfce.tfe.validation.StringValidation;

/**
 *
 * @author yema
 */
public class AjoutEcoleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AjoutEcoleJPanel
     */
    public AjoutEcoleJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identifiantecole = new javax.swing.JLabel();
        nomecole = new javax.swing.JLabel();
        adresseecole = new javax.swing.JLabel();
        telephoneecole = new javax.swing.JLabel();
        emailecole = new javax.swing.JLabel();
        nomdirecteur = new javax.swing.JLabel();
        annescolaire = new javax.swing.JLabel();
        idecoleTextField = new javax.swing.JTextField();
        nomecoleTextField = new javax.swing.JTextField();
        adresseTextField = new javax.swing.JTextField();
        telTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        nomdirecteurTextField = new javax.swing.JTextField();
        anneescolaireTextField = new javax.swing.JTextField();
        enregistrerecole = new javax.swing.JButton();
        annulerecole = new javax.swing.JButton();
        resetecole = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cdpostalTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vilTextField = new javax.swing.JTextField();

        identifiantecole.setText("Identifiant ecole:");

        nomecole.setText("Nom ecole:");

        adresseecole.setText("Adresse:");

        telephoneecole.setText("Telephone:");

        emailecole.setText("Email:");

        nomdirecteur.setText("Nom directeur:");

        annescolaire.setText("Annee scolaire:");

        enregistrerecole.setText("Enregistrer");
        enregistrerecole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerecoleActionPerformed(evt);
            }
        });

        annulerecole.setText("Annuler");

        resetecole.setText("Reset");

        jLabel1.setText("Code postal:");

        jLabel2.setText("Ville:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetecole)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enregistrerecole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(annulerecole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(annescolaire)
                                .addGap(26, 26, 26)
                                .addComponent(anneescolaireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identifiantecole)
                            .addComponent(nomecole)
                            .addComponent(adresseecole)
                            .addComponent(telephoneecole)
                            .addComponent(emailecole)
                            .addComponent(nomdirecteur)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomdirecteurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(idecoleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                        .addComponent(nomecoleTextField)
                                        .addComponent(adresseTextField)
                                        .addComponent(telTextField))
                                    .addComponent(vilTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cdpostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identifiantecole)
                    .addComponent(idecoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomecole)
                    .addComponent(nomecoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseecole)
                    .addComponent(adresseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdpostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(vilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneecole)
                    .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailecole)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomdirecteurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomdirecteur))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anneescolaireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annescolaire))
                .addGap(42, 42, 42)
                .addComponent(enregistrerecole)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerecole)
                    .addComponent(resetecole))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerecoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerecoleActionPerformed
        // TODO add your handling code here:
        Ecole ecole = new Ecole();
        String idecole = idecoleTextField.getText();
        ecole.setId(0);
        System.out.println(idecole);
        
         String nomecole = nomecoleTextField.getText();
        if(!StringValidation.VerifString(nomecole)){
             System.out.println(" NOM INCORRECT");}
        else{
            
            ecole.setNomecole(String.valueOf(nomecole));
            System.out.println("NOM CORRECT");
        }
        String adresseecole = adresseTextField.getText();
        ecole.setAdresseecole(adresseecole);
        System.out.println(adresseecole);
        
        
         String cdpostal = cdpostalTextField.getText();
         if (!CodePosalValidation.checkCodePostale(cdpostal)) {
            
            System.out.println("CODE POSTALE INCORRECT");
        } else {
            ecole.setCdpostal(Integer.valueOf(cdpostal));
            
            System.out.println("CODE POSTALE CORRECT");
            System.out.println(cdpostal);
        }
        
        
        
        
         String ville = vilTextField.getText();
         StringValidation.VerifString(ville);
         ecole.setVil(ville);
          
        
         String numtel = telTextField.getText();
          NumTelValidation.checkNumTel(numtel);
          numtel = numtel.replace("-", "");
          numtel = numtel.replace(".", "");
          numtel = numtel.replace("/", "");
          
          ecole.setTelecole(Integer.valueOf(numtel));
          System.out.println(numtel);
          
           String email = emailTextField.getText();
             if (!EmailValidation.validateEmailAddress(email)) {
            
            System.out.println("EMAIL INCORRECT");
        } else {
            ecole.setEmailEcole(String.valueOf(email));
            
            System.out.println("EMAIL CORRECT");
            System.out.println(email);  
                }
           
            String nomdirecteur = nomdirecteurTextField.getText();
                 if(!StringValidation.VerifString(nomdirecteur)){
                 System.out.println(" NOM INCORRECT");}
            else{
            
                ecole.setNomDirecteur(String.valueOf(nomdirecteur));
                System.out.println(nomdirecteur);
                }
                 
            String anneescolaire = anneescolaireTextField.getText();
            ecole.setAnneescolaire(anneescolaire);
            System.out.println(anneescolaire);
        
          
           EcoleDBHelper.addEcole(ecole);
        //   EcoleDBHelper.selectEcole(ecole);
    }//GEN-LAST:event_enregistrerecoleActionPerformed
 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresseTextField;
    private javax.swing.JLabel adresseecole;
    private javax.swing.JTextField anneescolaireTextField;
    private javax.swing.JLabel annescolaire;
    private javax.swing.JButton annulerecole;
    private javax.swing.JTextField cdpostalTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel emailecole;
    private javax.swing.JButton enregistrerecole;
    private javax.swing.JTextField idecoleTextField;
    private javax.swing.JLabel identifiantecole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nomdirecteur;
    private javax.swing.JTextField nomdirecteurTextField;
    private javax.swing.JLabel nomecole;
    private javax.swing.JTextField nomecoleTextField;
    private javax.swing.JButton resetecole;
    private javax.swing.JTextField telTextField;
    private javax.swing.JLabel telephoneecole;
    private javax.swing.JTextField vilTextField;
    // End of variables declaration//GEN-END:variables
}
