/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;

import be.isfce.tfe.metier.CarteCarburant;
import be.isfce.tfe.db.CarteCarburantDBHelper;
/**
 *
 * @author yema
 */
public class AjoutCarteCarburantJPanell extends javax.swing.JPanel {

    /**
     * Creates new form AjoutCarteCarburantJPanell
     */
    public AjoutCarteCarburantJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idcarte = new javax.swing.JLabel();
        kmutilisation = new javax.swing.JLabel();
        litrecarburant = new javax.swing.JLabel();
        numcartecarburantTextField = new javax.swing.JTextField();
        kmutilisationTextField = new javax.swing.JTextField();
        litrecarburantTextField = new javax.swing.JTextField();
        ajoutercarte = new javax.swing.JButton();
        anulerinfo = new javax.swing.JButton();
        initialiser = new javax.swing.JButton();

        idcarte.setText("Numero de carte:");

        kmutilisation.setText("Kmutilisation:");

        litrecarburant.setText("Litre de carburant:");

        ajoutercarte.setText("Enregister");
        ajoutercarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutercarteActionPerformed(evt);
            }
        });

        anulerinfo.setText("Annuler");

        initialiser.setText("Reset");
        initialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idcarte)
                            .addComponent(kmutilisation)
                            .addComponent(litrecarburant))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numcartecarburantTextField)
                            .addComponent(kmutilisationTextField)
                            .addComponent(litrecarburantTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajoutercarte)
                        .addGap(91, 91, 91)
                        .addComponent(anulerinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(initialiser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idcarte)
                    .addComponent(numcartecarburantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kmutilisation)
                    .addComponent(kmutilisationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(litrecarburant)
                    .addComponent(litrecarburantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutercarte)
                    .addComponent(anulerinfo)
                    .addComponent(initialiser))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialiserActionPerformed

    private void ajoutercarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutercarteActionPerformed
        // TODO add your handling code here:
        CarteCarburant cartecarburant = new CarteCarburant();
        String id = numcartecarburantTextField.getText();
        cartecarburant.setId(0);
        System.out.println(id);
        
       
        
        String kmutilisation = kmutilisationTextField.getText();
        cartecarburant.setKmUtilisation(Integer.valueOf(kmutilisation));
        System.out.println(kmutilisation);
        
        String litrecarburant = litrecarburantTextField.getText();
        cartecarburant.setLitreCarburant(Integer.valueOf(litrecarburant));
        System.out.println(litrecarburant);
        
          CarteCarburantDBHelper.addCarteCarburant(cartecarburant);
        // CarteCarburantDBHelper.selectCarteCarburant(cartecarburant);
       
        
    }//GEN-LAST:event_ajoutercarteActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutercarte;
    private javax.swing.JButton anulerinfo;
    private javax.swing.JLabel idcarte;
    private javax.swing.JButton initialiser;
    private javax.swing.JLabel kmutilisation;
    private javax.swing.JTextField kmutilisationTextField;
    private javax.swing.JLabel litrecarburant;
    private javax.swing.JTextField litrecarburantTextField;
    private javax.swing.JTextField numcartecarburantTextField;
    // End of variables declaration//GEN-END:variables
}
