/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;

import be.isfce.tfe.metier.CarteCarburant;
import be.isfce.tfe.metier.DocumentsAdministratifs;

/**
 *
 * @author yema
 */
public class AjoutDocumentsJPanell extends javax.swing.JPanel {

    /**
     * Creates new form AjoutDocumentsJPanell
     */
    public AjoutDocumentsJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iddocument = new javax.swing.JLabel();
        libelledocument = new javax.swing.JLabel();
        datedevaliditer = new javax.swing.JLabel();
        iddocumentTextField = new javax.swing.JTextField();
        libelleTextField = new javax.swing.JTextField();
        datevaliditerTextField = new javax.swing.JTextField();
        Ajouterdocument = new javax.swing.JToggleButton();
        Modifierdocument = new javax.swing.JToggleButton();
        supprimerdocument = new javax.swing.JToggleButton();
        rechercherdocument = new javax.swing.JToggleButton();
        jTextField4 = new javax.swing.JTextField();

        iddocument.setText("Id document:");

        libelledocument.setText("Libelle:");

        datedevaliditer.setText("Date de validiter:");

        iddocumentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddocumentTextFieldActionPerformed(evt);
            }
        });

        libelleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleTextFieldActionPerformed(evt);
            }
        });

        datevaliditerTextField.setText("jTextField3");
        datevaliditerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datevaliditerTextFieldActionPerformed(evt);
            }
        });

        Ajouterdocument.setText("Enregistrer");
        Ajouterdocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterdocumentActionPerformed(evt);
            }
        });

        Modifierdocument.setText("Reset");

        supprimerdocument.setText("Annuler");

        rechercherdocument.setText("Rechercher");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ajouterdocument, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modifierdocument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(supprimerdocument)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(iddocument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(libelledocument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datedevaliditer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rechercherdocument))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(datevaliditerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addComponent(libelleTextField)
                                .addComponent(iddocumentTextField)))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechercherdocument)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddocument)
                    .addComponent(iddocumentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libelledocument)
                    .addComponent(libelleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datedevaliditer)
                    .addComponent(datevaliditerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouterdocument)
                    .addComponent(Modifierdocument)
                    .addComponent(supprimerdocument))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iddocumentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddocumentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddocumentTextFieldActionPerformed

    private void libelleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libelleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libelleTextFieldActionPerformed

    private void datevaliditerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datevaliditerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datevaliditerTextFieldActionPerformed

    private void AjouterdocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterdocumentActionPerformed
        // TODO add your handling code here:
        DocumentsAdministratifs documents = new DocumentsAdministratifs();
        String id = iddocumentTextField.getText();
        documents.setId(Integer.valueOf(id));
        System.out.println(id);
        
         String libelle = libelleTextField.getText();
         documents.setLibelle(libelle);
          System.out.println(libelle);
    }//GEN-LAST:event_AjouterdocumentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Ajouterdocument;
    private javax.swing.JToggleButton Modifierdocument;
    private javax.swing.JLabel datedevaliditer;
    private javax.swing.JTextField datevaliditerTextField;
    private javax.swing.JLabel iddocument;
    private javax.swing.JTextField iddocumentTextField;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField libelleTextField;
    private javax.swing.JLabel libelledocument;
    private javax.swing.JToggleButton rechercherdocument;
    private javax.swing.JToggleButton supprimerdocument;
    // End of variables declaration//GEN-END:variables
}
