/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;

import be.isfce.tfe.db.CarburantUtilisationDBHelper;
import be.isfce.tfe.metier.CarburantUtilisation;

/**
 *
 * @author yema
 */
public class CarburantUtilisationJPanell extends javax.swing.JPanel {

    /**
     * Creates new form CarburantUtilisationJPanell
     */
    public CarburantUtilisationJPanell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idutilisationTextField = new javax.swing.JTextField();
        idcarteTextField = new javax.swing.JTextField();
        validiterjButton = new javax.swing.JButton();
        modifierjButton = new javax.swing.JButton();
        annulerjButton = new javax.swing.JButton();

        jLabel1.setText("Identifiant utilisation: ");

        jLabel2.setText("Identifiant carte:");

        validiterjButton.setText("Validiter");
        validiterjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validiterjButtonActionPerformed(evt);
            }
        });

        modifierjButton.setText("Modifier");

        annulerjButton.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annulerjButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modifierjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(validiterjButton)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idutilisationTextField)
                            .addComponent(idcarteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idutilisationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(idcarteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validiterjButton)
                    .addComponent(modifierjButton)
                    .addComponent(annulerjButton))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validiterjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validiterjButtonActionPerformed
        // TODO add your handling code here:
         CarburantUtilisation carburantutilisation = new CarburantUtilisation();
         String idutilisation = idutilisationTextField.getText();
         carburantutilisation.setIdutilisation(Integer.valueOf(idutilisation));
         System.out.println(idutilisation);
        
        String idcarte = idcarteTextField.getText();
        carburantutilisation.setIdcarte(Integer.valueOf(idcarte));
        System.out.println(idcarte);
        
        CarburantUtilisationDBHelper.addCarburantUtilisation(carburantutilisation); 
        CarburantUtilisationDBHelper.selectCarburantUtilisation(carburantutilisation);
    }//GEN-LAST:event_validiterjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerjButton;
    private javax.swing.JTextField idcarteTextField;
    private javax.swing.JTextField idutilisationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton modifierjButton;
    private javax.swing.JButton validiterjButton;
    // End of variables declaration//GEN-END:variables
}
