/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;
import be.isfce.tfe.controleur.UtilisationControleur;
import be.isfce.tfe.controleur.ValidationException;
import be.isfce.tfe.db.TestUtlisationCarte;
import be.isfce.tfe.metier.UtilisationCarte;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author yema
 */
public class InsertionCarteUtilisationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsertionCarteUtilisationJPanel
     */
    public InsertionCarteUtilisationJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        dateutiliqation = new javax.swing.JLabel();
        enregistrer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        datecarteutilisation = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        dateutiliqation.setText("Date utilisation:");

        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });

        jButton1.setText("Annuler");

        jButton2.setText("Modifier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(enregistrer)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateutiliqation)
                        .addGap(26, 26, 26)
                        .addComponent(datecarteutilisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateutiliqation)
                    .addComponent(datecarteutilisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enregistrer)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
       UtilisationCarte utilisationcarte = new UtilisationCarte();
       
         
        utilisationcarte.setIdutilisationcarte(0);
     
        
        Date dateUtilisationcarte = datecarteutilisation.getDate();
        if(dateUtilisationcarte!= null){
          utilisationcarte.setDateutilisation(dateUtilisationcarte);
            System.out.println(dateUtilisationcarte);
        }else{
            System.out.println("DATE UTILISATION  INCORRECTE");
        } 
        
         try {
          UtilisationControleur.estValide(utilisationcarte);
          TestUtlisationCarte.addUtilisationCarte(utilisationcarte );
          TestUtlisationCarte.selectUtilisationCarte(utilisationcarte);
        } 
         catch (ValidationException ex) 
         {
            //TODO Afficher message d'erreur
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_enregistrerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser datecarteutilisation;
    private javax.swing.JLabel dateutiliqation;
    private javax.swing.JButton enregistrer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    // End of variables declaration//GEN-END:variables
}
