/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.isfce.tfe.vue;

import be.isfce.tfe.db.HeureDETravailDBHelper;
import be.isfce.tfe.metier.HeureDeTravail;

/**
 *
 * @author yema
 */
public class InsertionHeuredetravailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsertionHeuredetravailJPanel
     */
    public InsertionHeuredetravailJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heurededebut = new javax.swing.JLabel();
        heuredefin = new javax.swing.JLabel();
        heurededebutTextField = new javax.swing.JTextField();
        heuredefinTextField = new javax.swing.JTextField();
        enregistrer = new javax.swing.JButton();
        annulerheuredetravail = new javax.swing.JButton();
        numeroopeartion = new javax.swing.JLabel();
        idheureTextField = new javax.swing.JTextField();

        heurededebut.setText("Heure de debut:");

        heuredefin.setText("Heure de fin:");

        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });

        annulerheuredetravail.setText("Annuler");

        numeroopeartion.setText("Numero operation:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heuredefin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroopeartion)
                            .addComponent(heurededebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(heurededebutTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(heuredefinTextField)
                            .addComponent(idheureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(annulerheuredetravail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroopeartion)
                    .addComponent(idheureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heurededebut)
                    .addComponent(heurededebutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(heuredefin)
                    .addComponent(heuredefinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(enregistrer)
                .addGap(18, 18, 18)
                .addComponent(annulerheuredetravail)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        // TODO add your handling code here:
        
        
        
         HeureDeTravail heuredetravail = new HeureDeTravail();
         
         String idheure = idheureTextField.getText();
         heuredetravail.setIdheuredetravail(0);
        System.out.println( idheure );
         
         String heurededebut = heurededebutTextField.getText();
         heuredetravail.setHeureDeDebut(String.valueOf(heurededebut));
         System.out.println(heurededebut);
         
         String heuredefin = heuredefinTextField.getText();
         heuredetravail.setHeureDeFin(String.valueOf(heuredefin));
         System.out.println(heuredefin);
        
         
         HeureDETravailDBHelper.addHeureDeTravail(heuredetravail); 
       //  HeureDETravailDBHelper.selectHeureDeTravail(heuredetravail);
    }//GEN-LAST:event_enregistrerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerheuredetravail;
    private javax.swing.JButton enregistrer;
    private javax.swing.JLabel heurededebut;
    private javax.swing.JTextField heurededebutTextField;
    private javax.swing.JLabel heuredefin;
    private javax.swing.JTextField heuredefinTextField;
    private javax.swing.JTextField idheureTextField;
    private javax.swing.JLabel numeroopeartion;
    // End of variables declaration//GEN-END:variables
}
